### PR TITLE
Migrate polymer 1.0

### PR DESCRIPTION
**Pull request by ThaumRystra**
Closes meteor-useraccounts/polymer#6, but requires Differential/meteor-vulcanize#24 to be closed before it can run on Meteor 1.2

### CODE REVIEW

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
...I'm having problem running the app.
After running `bower install` I'm getting

`Uncaught TypeError: Polymer is not a function`

and nothing is rendered.

It seems a load order problem, since after several errors while loading elements, the `Polymer` object is defined and you can get it from the browser console.

Any idea?

**Comment by ThaumRystra** [comment]
It seems to be the issue with vulcanize using outdated API that no longer works in 1.2, so Polymer never gets included.

I'm waiting on a pull request of mine to be merged so it can work in 1.2, but until then, you can clone [this branch](https://github.com/ThaumRystra/meteor-vulcanize/tree/fix-meteor-1.2) into the local packages folder and it should override vulcanize with a working version and then work properly.

I did try to convince it to run on an older version of Meteor, but I had no luck getting it to stay there.

**Comment by splendido** [comment]
Up and running! :-)
I also added some instructions to get your working copy of `differential vulcanize`, see https://github.com/meteor-useraccounts/boilerplates/commit/3f40c1dc5c35c374a0fa133c90ca9b0a656d3fc3

I was sure it was ok, but I had to check ;-)

Thanks again for the contribution!

**Comment by ThaumRystra** [comment]
:+1:
